### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by lmjaedentai** [pokurt/nekobinpy#1]
I get this error while running [example.py](https://github.com/pokurt/nekobinpy/blob/master/example.py) in my pc.

```py
PS D:\Desktop\coding\telegram> & d:/Desktop/coding/telegram/env/Scripts/python.exe d:/Desktop/coding/py/test.py
Traceback (most recent call last):
  File "d:\Desktop\coding\py\test.py", line 142, in <module>
    asyncio.run(main())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\Desktop\coding\py\test.py", line 119, in main
    neko = await nekobin.nekofy(
  File "D:\Desktop\coding\telegram\env\lib\site-packages\nekobin\client.py", line 52, in nekofy
    return Neko(**data)
  File "D:\Desktop\coding\telegram\env\lib\site-packages\nekobin\types.py", line 25, in __init__
    self.date = datetime.fromtimestamp(result["date"])
TypeError: an integer is required (got type str)
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000023154DEB310>
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed        
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
How can I fix it?

**Comment by smyhlin** [comment]
I fix this in my fork, check if u still need it

**Comment by smyhlin** [comment]
> I get this error while running [example.py](https://github.com/pokurt/nekobinpy/blob/master/example.py) in my pc.
> 
> ```python
> PS D:\Desktop\coding\telegram> & d:/Desktop/coding/telegram/env/Scripts/python.exe d:/Desktop/coding/py/test.py
> Traceback (most recent call last):
>   File "d:\Desktop\coding\py\test.py", line 142, in <module>
>     asyncio.run(main())
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "d:\Desktop\coding\py\test.py", line 119, in main
>     neko = await nekobin.nekofy(
>   File "D:\Desktop\coding\telegram\env\lib\site-packages\nekobin\client.py", line 52, in nekofy
>     return Neko(**data)
>   File "D:\Desktop\coding\telegram\env\lib\site-packages\nekobin\types.py", line 25, in __init__
>     self.date = datetime.fromtimestamp(result["date"])
> TypeError: an integer is required (got type str)
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000023154DEB310>
> Traceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
>     self._check_closed()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed        
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> ```
> 
> How can I fix it?

I fix this in my fork, check if u still need it
I try to contribute it, so wait in main page if author still alive
